### ISSUE TITLE
Update shared-mime-type-info

### ISSUE THREAD

**Issue by melloware** [overview/mime-types#12]
It's been a while since a release any chance you could update the mime type info and do a 1.0.3 release?

**Comment by melloware** [comment]
Looks like 2.2. is the latest release: https://gitlab.freedesktop.org/xdg/shared-mime-info/-/releases

**Comment by adamhooper** [comment]
Released v1.0.3 with shared-mime-info-2.2.

Thank you for bringing freshness to this project!

**Comment by melloware** [comment]
Appreciate all your work on this! its a great lib!
