### ISSUE TITLE
Crash on Android 6

### ISSUE THREAD

**Issue by MichaelBodnar** [overview/mime-types#17]
Hi there, the lib crashes on Android 5,6 with the following trace:
```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org.overviewproject.mime_types.-$$Lambda$MimeTypeDetector$jalwYQGXcFlX-jwVvtGHLx2cssI
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:298)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: org.overviewproject.mime_types.-$$Lambda$MimeTypeDetector$jalwYQGXcFlX-jwVvtGHLx2cssI
        at org.overviewproject.mime_types.MimeTypeDetector.detectMimeType(MimeTypeDetector.java:195)
        at org.overviewproject.mime_types.MimeTypeDetector.detectMimeType(MimeTypeDetector.java:223)
```
All other versions of Android (at least 8+) work fine

**Comment by MichaelBodnar** [comment]
I made some small research and found that in the library you use CompletableFuture.
The library has a restriction, in this case, because the CompletableFuture, the system supports starts from Android API 24(Android 7.0), all versions with API 24 will not work with the library.
It's info for those who plan to integrate the library into their Android projects.

Thanks.

**Comment by melloware** [comment]
I think you would have to submit a PR to fix this issue as I don't think Android was this libraries original concern.

**Comment by adamhooper** [comment]
Yes, a PR would be welcome.

Right now, the `detectMimeType()` method relies on `detectMimeTypeAsync()`. It doesn't have to: we could use a synchronous helper, `detectMimeTypeUsingFirstBytes(filename, bytes)` and rewrite both detect methods to rely on that helper after they call `getBytes()`. (Remember: neither detect method should call getBytes when the call isn't needed.)

I don't know how pervasive Android 5, 6 are, so I can't get excited about writing the code myself.

**Comment by benoitletondor** [comment]
Please note that there are also usage of `java.nio.file.Path` and `java.io.File.toPath()` APIs that aren't compatible with Android < 26

**Comment by adamhooper** [comment]
I am okay with supporting these operating systems. First, though, I want to
know: who uses them? When do we drop support?

**Comment by benoitletondor** [comment]
> who uses them?

Not sure how to answer this but one thing I can say is that being compatible with API < 26 is a bit conservative today. Being 26+ only seems like an ok choice for a library like yours. I just commented here since I saw the issue and I have the same problem but that doesn't mean it should be a priority for you

> When do we drop support?

As soon as you think it's too conservative, same as before I don't know if there's a good answer here

**Comment by melloware** [comment]
My two cents is android Lower than 26 is probably a small percentage of users.  Someone can always fork this library and make an Android specific version if they are so inclined.  Just my two cents...

**Comment by adamhooper** [comment]
Awesome, thanks! Well, if anybody wants to support Android <26 I'll gladly
merge a PR and release a new version, if the PR includes answers to those
questions :).
