### ISSUE TITLE
Yearly update?

### ISSUE THREAD

**Issue by melloware** [overview/mime-types#18]
Time for an update of shared lib and publish?  Just a friendly yearly reminder. 😬

**Comment by adamhooper** [comment]
Great idea. I'll get around to this in the coming days.

**Comment by melloware** [comment]
Bump?

**Comment by adamhooper** [comment]
Looked into it. It appears shared-mime-info 2.2 is the latest version. [ref](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/master/NEWS?ref_type=heads)

I've already documented the process of updating mime info, at https://github.com/overview/mime-types/blob/main/DEVELOP.md. I suggest a friendly ping to the shared-mime-info maintainers; I definitely mean for this package to track that one.

Closing this. Please open if a new shared-mime-info is released!

**Comment by boris-petrov** [comment]
@adamhooper 2.3 just came out! :smile: You might think about releasing a new version based on it. :)

**Comment by adamhooper** [comment]
Thank you for the ping -- released! I called it v2.0.0 because some commonly-used MIME types have changed. See CHANGELOG (or https://gitlab.freedesktop.org/xdg/shared-mime-info/-/releases/2.3 directly) for full notes.
