### ISSUE TITLE
apk file mimetype is not detected properly

### ISSUE THREAD

**Issue by boredval** [overview/mime-types#19]
As title says apk is treated as zip ,even tho apk has it own mime type.

**Comment by melloware** [comment]
Hopefully relate to just updating the new defintions: https://github.com/overview/mime-types/issues/18

**Comment by adamhooper** [comment]
So annoying! Please follow the instructions at https://github.com/overview/mime-types/blob/main/DEVELOP.md -- ping the shared-mime-info folks.

Alternatively, you can generate a `mime.cache` file. Edit `extra-mime-info.xml` and then run `rebuild-mime-cache.sh`. Unfortunately, the `mime.cache` is presently built in to this package's `.jar` file. I'd love to see a patch that adds support for user-supplied `mime.cache` files. I've outlined what the patch should look like in #5.

Closing this issue: `DEVELOP.md` describes one path to getting the mime type detected, and #5 shows another. I've learned my lesson already: I won't override the XDG shared-mime-info database in this repo.

**Comment by melloware** [comment]
@adamhooper that is a good idea.  I might put it on my list to try a PR if I can carve out time but no promises.  Thanks for all your effort on this project!

**Comment by adamhooper** [comment]
I just tested here ... any file with a name like `x.apk` (i.e., ending in `.apk`) will be detected as "application/vnd.android.package-archive". This has probably been the case for the entire lifetime of this repository.
